name: test-game
run-name: Testing ${{ github.actor }}'s Sprig game

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - samactions

permissions:
  contents: read
  pull-requests: read

jobs:
  test-game:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
      - name: Check Games
        run: deno run --allow-read tests/sprigfuzzy_workflow.js
